# Generated by Django 4.2.7 on 2023-11-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_created', models.DateTimeField(auto_now_add=True)),
                ('role_status_check', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['role_created'],
            },
        ),
    ]
