# Generated by Django 4.2.7 on 2023-11-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_permissions_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='modules_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
