# Generated by Django 4.2.7 on 2023-11-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_modules_modules_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['roles_created']},
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='permissions_checklist',
            new_name='modules_permissions_checklist',
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='roles_dp',
            new_name='modules_roles_dp',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='role_created',
            new_name='roles_created',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='role_name',
            new_name='roles_name',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='role_status_check',
            new_name='roles_status_check',
        ),
    ]
