# Generated by Django 4.2.7 on 2023-11-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_users_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['userprofile_created']},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='users_created',
            new_name='userprofile_created',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='users_roles_dp',
            new_name='userprofile_roles_dp',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='users_status',
            new_name='userprofile_status',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='userprofile_user',
        ),
    ]
